version: '3.7'
services:
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: example
      POSTGRES_USER: root
      POSTGRES_DB: sports
    ports:
      - '5432:5432'
  api:
    image: margins-api
    environment:
      POSTGRES_PASSWORD: example
      POSTGRES_USER: root
      POSTGRES_DB: sports
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
    depends_on:
      - 'db'
    ports:
      - '3000:3000'
